### ISSUE TITLE
build error when making curios item

### ISSUE THREAD

**Issue by Thunderrock424242** [NerdyPuzzle/Curios-API-plugin-MCreator#2]
Executing Gradle task: build 
Build info: MCreator 2024.2.29712, neoforge-1.20.6, 64-bit, 32487 MB, Windows 11, JVM 21.0.3, JAVA_HOME: C:\Users\rockm\OneDrive\Desktop\MCreator20242\jdk, started on: 2024-07-27-13:17:21 
Loaded APIs: curios_api 
 
Reusing configuration cache. 
> Task :processTestResources NO-SOURCE 
> Task :create1.20.6ClientExtraJar UP-TO-DATE 
> Task :neoFormListLibraries UP-TO-DATE 
> Task :cacheVersionManifest1.20.6 UP-TO-DATE 
> Task :cacheVersionExecutableClient1.20.6 UP-TO-DATE 
> Task :selectRawArtifactNg_dummy_ng.net.minecraft_client_1.20.6_client-extra UP-TO-DATE 
> Task :neoFormJoined1.20.6-20240429.153634ExtractNatives UP-TO-DATE 
> Task :neoFormJoined1.20.6-20240429.153634DownloadAssets UP-TO-DATE 
> Task :cacheVersionExecutableServer1.20.6 UP-TO-DATE 
> Task :cacheVersionMappingsClient1.20.6 UP-TO-DATE 
> Task :neoFormExtractServer UP-TO-DATE 
> Task :cacheVersionMappingsServer1.20.6 UP-TO-DATE 
> Task :neoFormMergeMappings UP-TO-DATE 
> Task :neoFormStripClient UP-TO-DATE 
> Task :neoFormStripServer UP-TO-DATE 
> Task :neoFormMerge UP-TO-DATE 
> Task :neoFormRename UP-TO-DATE 
> Task :neoFormDecompile UP-TO-DATE 
> Task :processResources UP-TO-DATE 
> Task :neoFormApplyForgesAccessTransformer UP-TO-DATE 
> Task :neoFormInject UP-TO-DATE 
> Task :neoFormPatch UP-TO-DATE 
> Task :neoFormPatchUserDev UP-TO-DATE 
> Task :neoFormApplyOfficialMappings UP-TO-DATE 
> Task :neoFormUnzipSources UP-TO-DATE 
> Task :neoFormRecompile UP-TO-DATE 
> Task :neoFormPackRecomp UP-TO-DATE 
> Task :supplyRawJarForneoFormJoined1.20.6-20240429.153634 UP-TO-DATE 
> Task :selectRawArtifactNg_dummy_ng.net.neoforged_neoforge_20.6.117 UP-TO-DATE 
> Task :writeMinecraftClasspathJunit UP-TO-DATE 
> Task :compileJava FAILED 
[C:\Users\rockm\MCreatorWorkspaces\wilderness_oddesy_api_neo\src\main\java\net\mcreator\wildernessoddesyapi\item\FireclanSpiritItem.java:4](file:///C:/Users/rockm/MCreatorWorkspaces/wilderness_oddesy_api_neo/src/main/java/net/mcreator/wildernessoddesyapi/item/FireclanSpiritItem.java:4): error: package top.theillusivec4.curios.api.type.capability does not exist 
import top.theillusivec4.curios.api.type.capability.ICurioItem; 
                                                   ^ 
[C:\Users\rockm\MCreatorWorkspaces\wilderness_oddesy_api_neo\src\main\java\net\mcreator\wildernessoddesyapi\item\FireclanSpiritItem.java:5](file:///C:/Users/rockm/MCreatorWorkspaces/wilderness_oddesy_api_neo/src/main/java/net/mcreator/wildernessoddesyapi/item/FireclanSpiritItem.java:5): error: package top.theillusivec4.curios.api does not exist 
import top.theillusivec4.curios.api.SlotContext; 
                                   ^ 
[C:\Users\rockm\MCreatorWorkspaces\wilderness_oddesy_api_neo\src\main\java\net\mcreator\wildernessoddesyapi\item\FireclanSpiritItem.java:13](file:///C:/Users/rockm/MCreatorWorkspaces/wilderness_oddesy_api_neo/src/main/java/net/mcreator/wildernessoddesyapi/item/FireclanSpiritItem.java:13): error: cannot find symbol 
public class FireclanSpiritItem extends Item implements ICurioItem { 
                                                        ^ 
  symbol: class ICurioItem 
[C:\Users\rockm\MCreatorWorkspaces\wilderness_oddesy_api_neo\src\main\java\net\mcreator\wildernessoddesyapi\item\FireclanSpiritItem.java:19](file:///C:/Users/rockm/MCreatorWorkspaces/wilderness_oddesy_api_neo/src/main/java/net/mcreator/wildernessoddesyapi/item/FireclanSpiritItem.java:19): error: cannot find symbol 
    public void curioTick(SlotContext slotContext, ItemStack stack) { 
                          ^ 
  symbol:   class SlotContext 
  location: class FireclanSpiritItem 
[C:\Users\rockm\MCreatorWorkspaces\wilderness_oddesy_api_neo\src\main\java\net\mcreator\wildernessoddesyapi\item\FireclanSpiritItem.java:18](file:///C:/Users/rockm/MCreatorWorkspaces/wilderness_oddesy_api_neo/src/main/java/net/mcreator/wildernessoddesyapi/item/FireclanSpiritItem.java:18): error: method does not override or implement a method from a supertype 
    @Override 
    ^ 
5 errors 
FAILURE: Build failed with an exception. 
* What went wrong: 
Execution failed for task ':compileJava'. 
> Compilation failed; see the compiler error output for details. 
* Try: 
> Run with --info option to get more log output. 
> Run with --scan to get full insights. 
BUILD FAILED in 1s 
30 actionable tasks: 1 executed, 29 up-to-date 
Configuration cache entry reused. 
 
BUILD FAILED 
Task completed in 3 seconds

![Screenshot 2024-07-27 131841](https://github.com/user-attachments/assets/74d81bf0-2dd5-4594-af28-2d020916e8c9)

**Comment by NerdyPuzzle** [comment]
Tried disabling and enabling the API again?

**Comment by Thunderrock424242** [comment]
> Tried disabling and enabling the API again?

Did that and it's still not working

**Comment by NerdyPuzzle** [comment]
Then your gradle is screwed up somehow

**Comment by Thunderrock424242** [comment]
> Then your gradle is screwed up somehow

Is this what my mcreator.gradle is supposed to look like?![image](https://github.com/user-attachments/assets/3d3c8268-b665-4762-b1ed-6ebd6fbb941f)

**Comment by Thunderrock424242** [comment]
I cleared my gradle cache and that fixes it
